feat: add custom controller gains
deib-polimi/kosmos pull request #44
Opened 2021-10-04 14:17 UTC by lterrac

Add Proportional and integral gain in `servicelevelagreements` CRD

2021-10-05 15:55 UTC, DragonBanana requested changes

2021-10-05 15:55 UTC, DragonBanana commented on config/crd/bases/systemautoscaler.polimi.it_servicelevelagreements.yaml
> -  preserveUnknownFields: false
we should add it back

2021-10-05 15:55 UTC, DragonBanana commented on config/crd/bases/systemautoscaler.polimi.it_podscales.yaml
> -  preserveUnknownFields: false
we should add it back

2021-11-02 13:51 UTC, DragonBanana approved these changes
LGTM

2021-11-02 15:10 UTC, lterrac commented on config/crd/bases/systemautoscaler.polimi.it_podscales.yaml
> -  preserveUnknownFields: false
Done

2021-11-02 15:16 UTC, DragonBanana requested changes
We should change the value to the new one with underscores or use the camel case one

2021-11-02 15:16 UTC, DragonBanana commented on config/crd/bases/systemautoscaler.polimi.it_servicelevelagreements.yaml
> +              recommenderLogic:
This default value will not work

2021-11-02 15:17 UTC, lterrac commented on config/crd/bases/systemautoscaler.polimi.it_servicelevelagreements.yaml
> +              recommenderLogic:
solved

2021-11-02 15:18 UTC, DragonBanana approved these changes
LGTM

2021-11-02 15:18 UTC, merged